const preguntasRespuestas = [
    { pregunta: 'Albania', respuesta: 'Tirana' },
    { pregunta: 'Alemania', respuesta: 'Berlín' },
    { pregunta: 'Andorra', respuesta: 'Andorra La Vieja' },
    { pregunta: 'Armenia', respuesta: 'Ereván' },
    { pregunta: 'Austria', respuesta: 'Viena' },
    { pregunta: 'Azerbaiyán', respuesta: 'Bakú' },
    { pregunta: 'Bélgica', respuesta: 'Bruselas' },
    { pregunta: 'Bielorrusia', respuesta: 'Minsk' },
    { pregunta: 'Bosnia y Herzegovina', respuesta: 'Sarajevo' },
    { pregunta: 'Bulgaria', respuesta: 'Sofía' },
    { pregunta: 'Chipre', respuesta: 'Nicosia' },
    { pregunta: 'Ciudad del Vaticano', respuesta: 'Ciudad del Vaticano' },
    { pregunta: 'Croacia', respuesta: 'Zagreb' },
    { pregunta: 'Dinamarca', respuesta: 'Copenhague' },
    { pregunta: 'Eslovaquia', respuesta: 'Bratislava' },
    { pregunta: 'Eslovenia', respuesta: 'Liubliana' },
    { pregunta: 'España', respuesta: 'Madrid' },
    { pregunta: 'Estonia', respuesta: 'Tallín' },
    { pregunta: 'Finlandia', respuesta: 'Helsinki' },
    { pregunta: 'Francia', respuesta: 'París' },
    { pregunta: 'Georgia', respuesta: 'Tiflis' },
    { pregunta: 'Grecia', respuesta: 'Atenas' },
    { pregunta: 'Hungría', respuesta: 'Budapest' },
    { pregunta: 'Irlanda', respuesta: 'Dublín' },
    { pregunta: 'Islandia', respuesta: 'Reikiavik' },
    { pregunta: 'Italia', respuesta: 'Roma' },
    { pregunta: 'Kazajistán', respuesta: 'Nursultán' },
    { pregunta: 'Letonia', respuesta: 'Riga' },
    { pregunta: 'Liechtenstein', respuesta: 'Vaduz' },
    { pregunta: 'Lituania', respuesta: 'Vilna' },
    { pregunta: 'Luxemburgo', respuesta: 'Luxemburgo' },
    { pregunta: 'Macedonia del Norte', respuesta: 'Skopie' },
    { pregunta: 'Malta', respuesta: 'La Valeta' },
    { pregunta: 'Moldavia', respuesta: 'Chisinau' },
    { pregunta: 'Mónaco', respuesta: 'Mónaco' },
    { pregunta: 'Montenegro', respuesta: 'Podgorica' },
    { pregunta: 'Noruega', respuesta: 'Oslo' },
    { pregunta: 'Países Bajos', respuesta: 'Ámsterdam' },
    { pregunta: 'Polonia', respuesta: 'Varsovia' },
    { pregunta: 'Portugal', respuesta: 'Lisboa' },
    { pregunta: 'Reino Unido', respuesta: 'Londres' },
    { pregunta: 'República Checa', respuesta: 'Praga' },
    { pregunta: 'Rumanía', respuesta: 'Bucarest' },
    { pregunta: 'Rusia', respuesta: 'Moscú' },
    { pregunta: 'San Marino', respuesta: 'San Marino' },
    { pregunta: 'Serbia', respuesta: 'Belgrado' },
    { pregunta: 'Suecia', respuesta: 'Estocolmo' },
    { pregunta: 'Suiza', respuesta: 'Berna' },
    { pregunta: 'Turquía', respuesta: 'Ankara' },
    { pregunta: 'Ucrania', respuesta: 'Kiev' }
  ];